"""
Django settings for seckill_shop project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-suk**-_j2#_!b%m0j!e1wc3(lq@**eu2vvd-d@7!9a61(m!=oq'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'shop',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'seckill_shop.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates']
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'seckill_shop.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'seckill_shop',
        'USER': 'root',
        'PASSWORD': '123456',
        'HOST': 'localhost',
        'PORT': '3306',
        'OPTIONS': {
            'charset': 'utf8mb4',
            'init_command': "SET time_zone='+08:00'",
        },
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'zh-hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# 配置Redis作为缓存后端
CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": "redis://127.0.0.1:6379/1",  # Redis数据库编号1
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
            "CONNECTION_POOL_KWARGS": {"max_connections": 100},  # 连接池配置
        }
    }
}

# Celery配置
CELERY_BROKER_URL = 'amqp://guest:guest@localhost:5672//'  # RabbitMQ作为消息代理
CELERY_RESULT_BACKEND = 'redis://127.0.0.1:6379/0'  # Redis作为结果后端
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = 'Asia/Shanghai'
CELERY_ENABLE_UTC = False
# RabbitMQ高级配置
CELERY_BROKER_POOL_LIMIT = 100  # 连接池限制
CELERY_BROKER_HEARTBEAT = 30  # 心跳检测
CELERY_BROKER_CONNECTION_TIMEOUT = 30  # 连接超时
CELERY_BROKER_CONNECTION_RETRY = True  # 自动重连
CELERY_BROKER_CONNECTION_MAX_RETRIES = 10  # 最大重试次数


# 支付宝沙箱配置
ALIPAY_SETTINGS = {
    "appid": "9021000155669214",
    "app_return_url": "http://公网地址/result/",    # 同步回调地址
    "app_notify_url": "http://公网地址/alipay/notify/",  # 异步回调地址
    "app_private_key_path": os.path.join(BASE_DIR, "keys/app_private_key.pem"),  # 应用私钥路径
    "alipay_public_key_path": os.path.join(BASE_DIR, "keys/alipay_public_key.pem"),  # 支付宝公钥路径
    "sign_type": "RSA2",  # 签名方式
    "debug": True,  # 沙箱环境为True
}


# 读取密钥内容
from Crypto.PublicKey import RSA
# 1. 读取应用私钥
with open(ALIPAY_SETTINGS['app_private_key_path'], 'r') as f:
    app_private_key_content = f.read()
    private_key = RSA.import_key(app_private_key_content) # 主要是对文件内容进行处理，移除空格，换行，以及类似-----BEGIN PUBLIC KEY-----的样式
    app_private_key = private_key.export_key().decode('utf-8')
    ALIPAY_SETTINGS['app_private_key'] = app_private_key
# 2. 读取支付宝公钥
with open(ALIPAY_SETTINGS['alipay_public_key_path'], 'r') as f:
    alipay_public_key_content = f.read()
    public_key = RSA.import_key(alipay_public_key_content)
    alipay_public_key = public_key.export_key().decode('utf-8')
    ALIPAY_SETTINGS['alipay_public_key'] = alipay_public_key
